# Docker-compose file building images for production use.
version: "3.8"
services:
    client:
        build:
            context: ./client/
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
    server:
        build:
            context: ./server/
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
